//Set ve.registry.localisation defaults
ve.registry.localisation = {
	//EN-GB (British English, Default)
	
	//ve.Component
	//DatavisSuite
	AxisSymbol_top: "Top",
	AxisSymbol_bottom: "Bottom",
	AxisSymbol_left: "Left",
	AxisSymbol_right: "Right",
	AxisSymbol_position: "Position",
	AxisSymbol_axis_ticks_data_series: "Axis Ticks (Data Series)",
	AxisSymbol_tooltip_axis_ticks_data_series: "Assigns a data series as axis ticks instead of manual inputs. Series is vertically aligned.",
	AxisSymbol_toast_cleared_data_series: "Cleared data series from axis ticks.",
	AxisSymbol_toast_invalid_data_series: "The data series you have selected is not valid.",
	AxisSymbol_name: "Name",
	AxisSymbol_name_gap: "Name Gap",
	AxisSymbol_start: "Start",
	AxisSymbol_middle: "Middle",
	AxisSymbol_end: "End",
	AxisSymbol_name_location: "Name Location",
	AxisSymbol_name_move_overlap: "Name Move Overlap",
	AxisSymbol_name_rotate: "Name Rotate",
	AxisSymbol_value: "Value",
	AxisSymbol_category: "Category",
	AxisSymbol_time: "Time",
	AxisSymbol_log: "Log",
	AxisSymbol_type: "Type",
	AxisSymbol_axis_ticks: "Axis Ticks",
	AxisSymbol_show_axis_label: "Show Axis Label",
	AxisSymbol_centre: "Centre",
	AxisSymbol_none: "None",
	AxisSymbol_align_max_label: "Align Max Label",
	AxisSymbol_align_min_label: "Align Min Label",
	AxisSymbol_custom_values: "Custom Values",
	AxisSymbol_formatter: "Formatter",
	AxisSymbol_tooltip_formatter: "Valid variables include {extraZ}, {index}, {value}, as well as time variables (i.e. {YYYY}) for 'time' axis.",
	AxisSymbol_hide_overlap: "Hide Overlap",
	AxisSymbol_inside: "Inside",
	AxisSymbol_interval: "Interval",
	AxisSymbol_margin: "Margin",
	AxisSymbol_rotate: "Rotate",
	AxisSymbol_show_max_label: "Show Max Label",
	AxisSymbol_show_min_label: "Show Min Label",
	AxisSymbol_label_symbol: "Label Symbol",
	AxisSymbol_stroke_symbol: "Stroke Symbol",
	AxisSymbol_axis_label: "Axis Label",
	AxisSymbol_show: "Show",
	AxisSymbol_on_zero: "On Zero",
	AxisSymbol_on_zero_axis_index: "On Zero Axis Index",
	AxisSymbol_symbol_none_none: "None, None",
	AxisSymbol_symbol_arrow_arrow: "Arrow, Arrow",
	AxisSymbol_symbol_arrow_none: "Arrow, None",
	AxisSymbol_symbol_none_arrow: "None, Arrow",
	AxisSymbol_x: "X",
	AxisSymbol_y: "Y",
	AxisSymbol_symbol_size: "Symbol Size",
	AxisSymbol_symbol_offset: "Symbol Offset",
	AxisSymbol_axis_line: "Axis Line",
	AxisSymbol_onhover_emphasis: "Onhover Emphasis",
	AxisSymbol_onhover_tooltip: "Onhover Tooltip",
	AxisSymbol_shadow_blur: "Shadow Blur",
	AxisSymbol_shadow_colour: "Shadow Colour",
	AxisSymbol_shadow_offset_x: "Shadow Offset X",
	AxisSymbol_shadow_offset_y: "Shadow Offset Y",
	AxisSymbol_snap_to: "Snap To",
	AxisSymbol_status: "Status",
	AxisSymbol_line: "Line",
	AxisSymbol_shadow: "Shadow",
	AxisSymbol_z_index: "Z-Index",
	AxisSymbol_axis_pointer: "Axis Pointer",
	AxisSymbol_align_with_label: "Align with Label",
	AxisSymbol_length: "Length",
	AxisSymbol_minor_split_line: "Minor Split Line",
	AxisSymbol_split_number: "Split Number",
	AxisSymbol_minor_tick: "Minor Tick",
	AxisSymbol_axis_tick: "Axis Tick",
	AxisSymbol_expand_on_click: "Expand On Click",
	AxisSymbol_point_symbol: "Point Symbol",
	AxisSymbol_zigzag_amplitude: "Zigzag Amplitude",
	AxisSymbol_zigzag_max_span: "Zigzag Max Span",
	AxisSymbol_zigzag_min_span: "Zigzag Min Span",
	AxisSymbol_zigzag_z_index: "Zigzag Z-Index",
	AxisSymbol_break_area: "Break Area",
	AxisSymbol_breaks: "Breaks",
	AxisSymbol_ellipsis: "Ellipsis",
	AxisSymbol_max_width: "Max Width",
	AxisSymbol_name_truncate: "Name Truncate",
	AxisSymbol_auto: "Auto",
	AxisSymbol_true: "True",
	AxisSymbol_false: "False",
	AxisSymbol_move_overlap: "Move Overlap",
	AxisSymbol_overlap: "Overlap",
	AxisSymbol_fill_symbol: "Fill Symbol",
	AxisSymbol_split_area: "Split Area",
	AxisSymbol_show_max_line: "Show Max Line",
	AxisSymbol_show_min_line: "Show Min Line",
	AxisSymbol_split_line: "Split Line",
	AxisSymbol_align_ticks: "Align Ticks",
	AxisSymbol_boundary_gap: "Boundary Gap",
	AxisSymbol_boundary_gap_x_y: "Boundary Gap X, Y",
	AxisSymbol_grid_index: "Grid Index",
	AxisSymbol_interactive: "Interactive",
	AxisSymbol_inverse: "Inverse",
	AxisSymbol_log_base: "Log Base",
	AxisSymbol_jitter: "Jitter",
	AxisSymbol_tooltip_jitter: "Applicable only to Scatterplot.",
	AxisSymbol_jitter_margin: "Jitter Margin",
	AxisSymbol_jitter_overlap: "Jitter Overlap",
	AxisSymbol_max: "Max",
	AxisSymbol_max_interval: "Max Interval",
	AxisSymbol_min: "Min",
	AxisSymbol_min_interval: "Min Interval",
	AxisSymbol_offset: "Offset",
	AxisSymbol_scale: "Scale",
	AxisSymbol_silent: "Silent",
	AxisSymbol_start_value: "Start Value",
	AxisSymbol_text_symbol: "Text Symbol",
	AxisSymbol_styling_advanced: "Styling (Advanced)",
	AxisSymbol_tooltip_symbol: "Tooltip Symbol",
	AxisSymbol_tooltip: "Tooltip",
	AxisSymbol_delay: "Delay",
	AxisSymbol_delay_update: "Delay Update",
	AxisSymbol_duration: "Duration",
	AxisSymbol_duration_update: "Duration Update",
	AxisSymbol_easing_linear: "Linear",
	AxisSymbol_easing_quadratic_in: "Quadratic In",
	AxisSymbol_easing_quadratic_out: "Quadratic Out",
	AxisSymbol_easing_quadratic_in_out: "Quadratic In Out",
	AxisSymbol_easing_cubic_in: "Cubic In",
	AxisSymbol_easing_cubic_out: "Cubic Out",
	AxisSymbol_easing_cubic_in_out: "Cubic In Out",
	AxisSymbol_easing_quartic_in: "Quartic In",
	AxisSymbol_easing_quartic_out: "Quartic Out",
	AxisSymbol_easing_quartic_in_out: "Quartic In Out",
	AxisSymbol_easing_quintic_in: "Quintic In",
	AxisSymbol_easing_quintic_out: "Quintic Out",
	AxisSymbol_easing_quintic_in_out: "Quintic In Out",
	AxisSymbol_easing_sinusoidal_in: "Sinusoidal In",
	AxisSymbol_easing_sinusoidal_out: "Sinusoidal Out",
	AxisSymbol_easing_sinusoidal_in_out: "Sinusoidal In Out",
	AxisSymbol_easing_exponential_in: "Exponential In",
	AxisSymbol_easing_exponential_out: "Exponential Out",
	AxisSymbol_easing_exponential_in_out: "Exponential In Out",
	AxisSymbol_easing_circular_in: "Circular In",
	AxisSymbol_easing_circular_out: "Circular Out",
	AxisSymbol_easing_circular_in_out: "Circular In Out",
	AxisSymbol_easing_elastic_in: "Elastic In",
	AxisSymbol_easing_elastic_out: "Elastic Out",
	AxisSymbol_easing_elastic_in_out: "Elastic In Out",
	AxisSymbol_easing_back_in: "Back In",
	AxisSymbol_easing_back_out: "Back Out",
	AxisSymbol_easing_back_in_out: "Back In Out",
	AxisSymbol_easing_bounce_in: "Bounce In",
	AxisSymbol_easing_bounce_out: "Bounce Out",
	AxisSymbol_easing_bounce_in_out: "Bounce In Out",
	AxisSymbol_easing: "Easing",
	AxisSymbol_easing_update: "Easing Update",
	AxisSymbol_animation: "Animation",
	AxisSymbol_axis_symbol: "Axis Symbol",
	
	AxisSymbol_Polar_id: "ID",
	AxisSymbol_Polar_centre: "Centre",
	AxisSymbol_Polar_calendar: "Calendar",
	AxisSymbol_Polar_matrix: "Matrix",
	AxisSymbol_Polar_none: "None",
	AxisSymbol_Polar_coordinate_system: "Coordinate System",
	AxisSymbol_Polar_radius: "Radius",
	AxisSymbol_Polar_z_index: "Z Index",
	AxisSymbol_Polar_calendar_id: "Calendar ID",
	AxisSymbol_Polar_calendar_index: "Calendar Index",
	AxisSymbol_Polar_matrix_io: "Matrix IO",
	AxisSymbol_Polar_matrix_index: "Matrix Index",
	AxisSymbol_Polar_label_symbol: "Label Symbol",
	AxisSymbol_Polar_tooltip: "Tooltip",
	AxisSymbol_Polar_axis_symbol_polar: "Axis Symbol (Polar)",
	
	FillSymbol_fill_colour: "Fill Colour",
	FillSymbol_auto: "Auto",
	FillSymbol_end: "End",
	FillSymbol_start: "Start",
	FillSymbol_origin: "Origin",
	FillSymbol_opacity: "Opacity",
	FillSymbol_shadow_blur: "Shadow Blur",
	FillSymbol_shadow_offset_x: "Shadow Offset X",
	FillSymbol_shadow_offset_y: "Shadow Offset Y",
	FillSymbol_fill_symbol: "Fill Symbol",
	
	LabelSymbol_show: "Show",
	LabelSymbol_colour: "Colour",
	LabelSymbol_formatter: "Formatter",
	LabelSymbol_font_family: "Font Family",
	LabelSymbol_font_size: "Font Size",
	LabelSymbol_normal: "Normal",
	LabelSymbol_italic: "Italic",
	LabelSymbol_oblique: "Oblique",
	LabelSymbol_font_style: "Font Style",
	LabelSymbol_light: "Light",
	LabelSymbol_medium: "Medium",
	LabelSymbol_bold: "Bold",
	LabelSymbol_font_weight: "Font Weight",
	LabelSymbol_height: "Height",
	LabelSymbol_width: "Width",
	LabelSymbol_text_options: "Text Options",
	LabelSymbol_background_colour: "Background Colour",
	LabelSymbol_border_colour: "Border Colour",
	LabelSymbol_border_dash_offset: "Border Dash Offset",
	LabelSymbol_border_radius: "Border Radius",
	LabelSymbol_dashed: "Dashed",
	LabelSymbol_dotted: "Dotted",
	LabelSymbol_solid: "Solid",
	LabelSymbol_border_type: "Border Type",
	LabelSymbol_border_width: "Border Width",
	LabelSymbol_distance: "Distance",
	LabelSymbol_ellipsis: "Ellipsis",
	LabelSymbol_line_height: "Line Height",
	LabelSymbol_offset_x: "Offset X",
	LabelSymbol_offset_y: "Offset Y",
	LabelSymbol_break: "Break",
	LabelSymbol_break_all: "Break All",
	LabelSymbol_none: "None",
	LabelSymbol_truncate: "Truncate",
	LabelSymbol_overflow: "Overflow",
	LabelSymbol_minimum_margin: "Minimum Margin",
	LabelSymbol_padding: "Padding",
	LabelSymbol_bottom: "Bottom",
	LabelSymbol_inside: "Inside",
	LabelSymbol_inside_bottom: "Inside Bottom",
	LabelSymbol_inside_bottom_left: "Inside Bottom Left",
	LabelSymbol_inside_bottom_right: "Inside Bottom Right",
	LabelSymbol_inside_left: "Inside Left",
	LabelSymbol_inside_right: "Inside Right",
	LabelSymbol_inside_top: "Inside Top",
	LabelSymbol_inside_top_left: "Inside Top Left",
	LabelSymbol_inside_top_right: "Inside Top Right",
	LabelSymbol_left: "Left",
	LabelSymbol_right: "Right",
	LabelSymbol_top: "Top",
	LabelSymbol_position: "Position",
	LabelSymbol_rotate: "Rotate",
	LabelSymbol_centre: "Centre",
	LabelSymbol_text_align_horizontal: "Text Align (Horizontal)",
	LabelSymbol_middle: "Middle",
	LabelSymbol_text_align_vertical: "Text Align (Vertical)",
	LabelSymbol_text_border_colour: "Text Border Colour",
	LabelSymbol_text_border_dash_offset: "Text Border Dash Offset",
	LabelSymbol_text_border_type: "Text Border Type",
	LabelSymbol_text_border_width: "Text Border Width",
	LabelSymbol_text_margin_x: "Text Margin X",
	LabelSymbol_text_margin_y: "Text Margin Y",
	LabelSymbol_text_shadow_blur: "Text Shadow Blur",
	LabelSymbol_text_shadow_offset_x: "Text Shadow Offset X",
	LabelSymbol_text_shadow_offset_y: "Text Shadow Offset Y",
	LabelSymbol_text_style: "Text Style",
	LabelSymbol_shadow_blur: "Shadow Blur",
	LabelSymbol_shadow_colour: "Shadow Colour",
	LabelSymbol_shadow_offset_x: "Shadow Offset X",
	LabelSymbol_shadow_offset_y: "Shadow Offset Y",
	LabelSymbol_shadow: "Shadow",
	LabelSymbol_label_symbol: "Label Symbol",
	
	//ve.Component
	//FileExplorer
	FileExplorer_are_you_sure_delete: "Are you sure you want to delete the following files?<br><br>£1£<br><br>This action cannot be undone!",
	FileExplorer_are_you_sure_copy_paste: "Are you sure you want to copy/paste £1£ file(s) to £2£?",
	FileExplorer_are_you_sure_load: "Are you sure you want to load £1£?",
	FileExplorer_back: "Back",
	FileExplorer_cannot_create_unnamed_folder: "You cannot create a folder with no name.",
	FileExplorer_clear_clipboard: "Clear Clipboard",
	FileExplorer_clipboard: "Clipboard",
	FileExplorer_clipboard_is_empty: "Clipboard is empty.",
	FileExplorer_create_a_new_file: "Create a new file:",
	FileExplorer_create_new_file: "Create New File",
	FileExplorer_create_new_folder: "Create New Folder",
	FileExplorer_create_a_new_folder: "Create a new folder:",
	FileExplorer_created_empty_text_file: "Created empty text file at: £1£",
	FileExplorer_cut_paste_files: "Cut/Paste £1£ files",
	FileExplorer_cut_selected: "Cut Selected",
	FileExplorer_confirm: "Confirm",
	FileExplorer_copied_elements_to_clipboard: "Copied £1£ elements to clipboard.",
	FileExplorer_copy_selected: "Copy Selected",
	FileExplorer_delete_files: "Delete £1£ files",
	FileExplorer_delete_selected: "Delete Selected",
	FileExplorer_do_you_want_to_overwrite_file: "File already exists. Do you want to overwrite it?",
	FileExplorer_elements_selected: "£1£ Element(s) selected",
	FileExplorer_error_load: "Error upon loading file £1£: £2£",
	FileExplorer_error_load_save_file: "Error loading savefile",
	FileExplorer_load_save_file: "Load Savefile",
	FileExplorer_loaded_save_file: "Loaded savefile £1£",
	FileExplorer_move_files: "Move £1£ files",
	FileExplorer_move_selected: "Move Selected",
	FileExplorer_paste_clipboard: "Paste Clipboard",
	FileExplorer_paste_files: "Paste £1£ files",
	FileExplorer_rename: "Rename",
	FileExplorer_save_file: "Save File",
	FileExplorer_save_file_as: "Save file as:",
	FileExplorer_select: "Select",
	FileExplorer_specified_file_path_already_exists: "The specified path already exists as a file! Delete it first before creating a new file with the same name.",
	FileExplorer_successfully_saved_file_as: "Successfully saved file as: £1£",
	
	//FileExplorer (File Operations)
	FileExplorer_copying_files_to: "Copying £1£ file(s) to £2£",
	FileExplorer_copying_to: "Copying £1£ to £2£",
	FileExplorer_deleting_files: "Deleting £1£ file(s)",
	FileExplorer_deleting_path: "Deleting £1£",
	FileExplorer_done: "Done",
	FileExplorer_error: "ERROR: £1£",
	FileExplorer_error_could_not_be_renamed: "ERROR: £1£ could not be renamed: £2£",
	FileExplorer_eta_remaining: "£1£% - £2£ remaining",
	FileExplorer_finished_moving_files: "Finished moving files",
	FileExplorer_of_progress: "(£1£ of £2£)",
	FileExplorer_overwrite: "Overwrite",
	FileExplorer_overwrite_all: "Overwrite All",
	FileExplorer_moved_files: "Finished moving £1£ file(s) to £2£",
	FileExplorer_rename_file: "Rename File",
	FileExplorer_rename_file_to: "Rename file £1£ to:",
	FileExplorer_skip: "Skip",
	
	PointSymbol_butt: "Butt",
	PointSymbol_round: "Round",
	PointSymbol_square: "Square",
	PointSymbol_border_cap: "Border Cap",
	PointSymbol_border_colour: "Border Colour",
	PointSymbol_border_dash_offset: "Border Dash Offset",
	PointSymbol_bevel: "Bevel",
	PointSymbol_miter: "Miter",
	PointSymbol_border_join: "Border Join",
	PointSymbol_border_miter_limit: "Border Miter Limit",
	PointSymbol_dashed: "Dashed",
	PointSymbol_dotted: "Dotted",
	PointSymbol_solid: "Solid",
	PointSymbol_border_type: "Border Type",
	PointSymbol_border_width: "Border Width",
	PointSymbol_colour: "Colour",
	PointSymbol_background_colour: "Background Colour",
	PointSymbol_dash_array_x: "Dash Array X",
	PointSymbol_dash_array_y: "Dash Array Y",
	PointSymbol_max_tile_height: "Max Tile Height",
	PointSymbol_max_tile_width: "Max Tile Width",
	PointSymbol_rotation: "Rotation",
	PointSymbol_arrow: "Arrow",
	PointSymbol_circle: "Circle",
	PointSymbol_diamond: "Diamond",
	PointSymbol_none: "None",
	PointSymbol_pin: "Pin",
	PointSymbol_triangle: "Triangle",
	PointSymbol_rectangle: "Rectangle",
	PointSymbol_rounded_rectangle: "Rounded Rectangle",
	PointSymbol_symbol: "Symbol",
	PointSymbol_symbol_keep_aspect: "Symbol Keep Aspect",
	PointSymbol_symbol_size: "Symbol Size",
	PointSymbol_decal: "Decal",
	PointSymbol_opacity: "Opacity",
	PointSymbol_shadow_blur: "Shadow Blur",
	PointSymbol_shadow_colour: "Shadow Colour",
	PointSymbol_shadow_offset_x: "Shadow Offset X",
	PointSymbol_shadow_offset_y: "Shadow Offset Y",
	PointSymbol_point_symbol: "Point Symbol",
	
	StrokeSymbol_stroke_colour: "Stroke Colour",
	StrokeSymbol_stroke_opacity: "Stroke Opacity",
	StrokeSymbol_dashed: "Dashed",
	StrokeSymbol_dotted: "Dotted",
	StrokeSymbol_solid: "Solid",
	StrokeSymbol_stroke_pattern: "Stroke Pattern",
	StrokeSymbol_stroke_width: "Stroke Width",
	StrokeSymbol_butt: "Butt",
	StrokeSymbol_round: "Round",
	StrokeSymbol_square: "Square",
	StrokeSymbol_stroke_cap: "Stroke Cap",
	StrokeSymbol_stroke_dash_offset: "Stroke Dash Offset",
	StrokeSymbol_bevel: "Bevel",
	StrokeSymbol_miter: "Miter",
	StrokeSymbol_stroke_join: "Stroke Join",
	StrokeSymbol_stroke_miter_limit: "Stroke Miter Limit",
	StrokeSymbol_stroke_style: "Stroke Style",
	StrokeSymbol_shadow_blur: "Shadow Blur",
	StrokeSymbol_shadow_offset_x: "Shadow Offset X",
	StrokeSymbol_shadow_offset_y: "Shadow Offset Y",
	StrokeSymbol_stroke_shadow: "Stroke Shadow",
	StrokeSymbol_stroke_symbol: "Stroke Symbol",
	
	TextSymbol_colour: "Colour",
	TextSymbol_ellipsis: "Ellipsis",
	TextSymbol_font_family: "Font Family",
	TextSymbol_font_size: "Font Size",
	TextSymbol_normal: "Normal",
	TextSymbol_italic: "Italic",
	TextSymbol_oblique: "Oblique",
	TextSymbol_font_style: "Font Style",
	TextSymbol_bold: "Bold",
	TextSymbol_bolder: "Bolder",
	TextSymbol_lighter: "Lighter",
	TextSymbol_font_weight: "Font Weight",
	TextSymbol_height: "Height",
	TextSymbol_break: "Break",
	TextSymbol_break_all: "Break All",
	TextSymbol_none: "None",
	TextSymbol_truncate: "Truncate",
	TextSymbol_overflow: "Overflow",
	TextSymbol_text_border_colour: "Text Border Colour",
	TextSymbol_text_border_dash_offset: "Text Border Dash Offset",
	TextSymbol_solid: "Solid",
	TextSymbol_dashed: "Dashed",
	TextSymbol_dotted: "Dotted",
	TextSymbol_text_border_type: "Text Border Type",
	TextSymbol_text_border_width: "Text Border Width",
	TextSymbol_shadow_blur: "Shadow Blur",
	TextSymbol_text_shadow_colour: "Text Shadow Colour",
	TextSymbol_shadow_offset_x: "Shadow Offset X",
	TextSymbol_shadow_offset_y: "Shadow Offset Y",
	TextSymbol_width: "Width",
	TextSymbol_text_symbol: "Text Symbol",
	
	TitleSymbol_id: "ID",
	TitleSymbol_show: "Show",
	TitleSymbol_name: "Name",
	TitleSymbol_link: "Link",
	TitleSymbol_blank: "Blank",
	TitleSymbol_self: "Self",
	TitleSymbol_target: "Target",
	TitleSymbol_title_symbol: "Title Symbol",
	TitleSymbol_x: "X",
	TitleSymbol_y: "Y",
	TitleSymbol_calendar: "Calendar",
	TitleSymbol_matrix: "Matrix",
	TitleSymbol_none: "None",
	TitleSymbol_coordinate_system: "Coordinate System",
	TitleSymbol_box: "Box",
	TitleSymbol_data: "Data",
	TitleSymbol_coordinate_system_usage: "Coordinate System Usage",
	TitleSymbol_coordinates: "Coordinates",
	TitleSymbol_bottom: "Bottom",
	TitleSymbol_left: "Left",
	TitleSymbol_right: "Right",
	TitleSymbol_top: "Top",
	TitleSymbol_position: "Position",
	TitleSymbol_background_colour: "Background Colour",
	TitleSymbol_border_colour: "Border Colour",
	TitleSymbol_border_radius: "Border Radius",
	TitleSymbol_border_width: "Border Width",
	TitleSymbol_shadow_blur: "Shadow Blur",
	TitleSymbol_shadow_colour: "Shadow Colour",
	TitleSymbol_shadow_offset_x: "Shadow Offset X",
	TitleSymbol_shadow_offset_y: "Shadow Offset Y",
	TitleSymbol_styling: "Styling",
	TitleSymbol_calendar_id: "Calendar ID",
	TitleSymbol_calendar_index: "Calendar Index",
	TitleSymbol_item_gap: "Item Gap",
	TitleSymbol_matrix_io: "Matrix IO",
	TitleSymbol_matrix_index: "Matrix Index",
	TitleSymbol_padding: "Padding",
	TitleSymbol_auto: "Auto",
	TitleSymbol_centre: "Centre",
	TitleSymbol_text_align: "Text Align",
	TitleSymbol_middle: "Middle",
	TitleSymbol_text_vertical_align: "Text Vertical Align",
	TitleSymbol_trigger_event: "Trigger Event",
	TitleSymbol_z_index: "Z Index",
	TitleSymbol_z_level: "Z Level",
	TitleSymbol_styling_advanced: "Styling (Advanced)",
	TitleSymbol_subtitle: "Subtitle",
	TitleSymbol_sublink: "Sublink",
	TitleSymbol_subtarget: "Subtarget",
	TitleSymbol_subtitle_symbol: "Subtitle Symbol",
	
	TooltipSymbol_show: "Show",
	TooltipSymbol_axis: "Axis",
	TooltipSymbol_item: "Item",
	TooltipSymbol_none: "None",
	TooltipSymbol_trigger: "Trigger",
	TooltipSymbol_always_show_content: "Always Show Content",
	TooltipSymbol_class_name: "Class Name",
	TooltipSymbol_confine: "Confine",
	TooltipSymbol_display_transition: "Display Transition",
	TooltipSymbol_enterable: "Enterable",
	TooltipSymbol_hide_delay: "Hide Delay",
	TooltipSymbol_x: "X",
	TooltipSymbol_y: "Y",
	TooltipSymbol_position: "Position",
	TooltipSymbol_show_content: "Show Content",
	TooltipSymbol_show_delay: "Show Delay",
	TooltipSymbol_transition_duration: "Transition Duration",
	TooltipSymbol_click: "Click",
	TooltipSymbol_mousemove: "Mousemove",
	TooltipSymbol_mousemove_click: "Mousemove, Click",
	TooltipSymbol_trigger_on: "Trigger On",
	TooltipSymbol_html: "HTML",
	TooltipSymbol_rich_text: "Rich Text",
	TooltipSymbol_render_mode: "Render Mode",
	TooltipSymbol_label_symbol: "Label Symbol",
	TooltipSymbol_onhover_emphasis: "Onhover Emphasis",
	TooltipSymbol_onhover_tooltip: "Onhover Tooltip",
	TooltipSymbol_shadow_blur: "Shadow Blur",
	TooltipSymbol_shadow_colour: "Shadow Colour",
	TooltipSymbol_shadow_offset_x: "Shadow Offset X",
	TooltipSymbol_shadow_offset_y: "Shadow Offset Y",
	TooltipSymbol_snap_to: "Snap To",
	TooltipSymbol_status: "Status",
	TooltipSymbol_stroke_symbol: "Stroke Symbol",
	TooltipSymbol_line: "Line",
	TooltipSymbol_shadow: "Shadow",
	TooltipSymbol_type: "Type",
	TooltipSymbol_value: "Value",
	TooltipSymbol_z_index: "Z-Index",
	TooltipSymbol_axis_pointer: "Axis Pointer",
	TooltipSymbol_background_colour: "Background Colour",
	TooltipSymbol_background_opacity: "Background Opacity",
	TooltipSymbol_border_colour: "Border Colour",
	TooltipSymbol_border_width: "Border Width",
	TooltipSymbol_formatter: "Formatter",
	TooltipSymbol_tooltip_formatter: "{a} = Series Name<br>{b} = Name of a data item<br>{c} = Value of a data item<br>{@xxx} - The value of a dimension named 'xxx'<br>{@[n]} - The value of a dimension at the index of n.",
	TooltipSymbol_order_series_asc: "Series Ascending",
	TooltipSymbol_order_series_desc: "Series Descending",
	TooltipSymbol_order_value_asc: "Value Ascending",
	TooltipSymbol_order_value_desc: "Value Descending",
	TooltipSymbol_order: "Order",
	TooltipSymbol_padding: "Padding",
	TooltipSymbol_text_symbol: "Text Symbol",
	TooltipSymbol_tooltip_symbol: "Tooltip Symbol",
	
	VisualMapSymbol_gt: ">",
	VisualMapSymbol_lte: "<=",
	VisualMapSymbol_x: "X",
	VisualMapSymbol_y: "Y",
	VisualMapSymbol_centre: "Centre",
	VisualMapSymbol_bottom: "Bottom",
	VisualMapSymbol_left: "Left",
	VisualMapSymbol_top: "Top",
	VisualMapSymbol_right: "Right",
	VisualMapSymbol_position: "Position",
	VisualMapSymbol_pieces: "Pieces",
	VisualMapSymbol_local_piece: "Local Piece",
	VisualMapSymbol_visual_map_symbol: "Visual Map Symbol",
	
	SeriesSymbol_bar_category_gap: "Bar Category Gap",
	SeriesSymbol_bar_gap: "Bar Gap",
	SeriesSymbol_bar_max_width: "Bar Max Width",
	SeriesSymbol_bar_min_angle: "Bar Min Angle",
	SeriesSymbol_bar_min_height: "Bar Min Height",
	SeriesSymbol_bar_min_width: "Bar Min Width",
	SeriesSymbol_bar_width: "Bar Width",
	SeriesSymbol_round_cap: "Round Cap",
	SeriesSymbol_show_background: "Show Background",
	SeriesSymbol_bar_symbol: "Bar Symbol",
	SeriesSymbol_clockwise: "Clockwise",
	SeriesSymbol_empty_circle_symbol: "Empty Circle Symbol",
	SeriesSymbol_end_angle: "End Angle",
	SeriesSymbol_min_angle: "Min Angle",
	SeriesSymbol_min_show_label_angle: "Min Show Label Angle",
	SeriesSymbol_area: "Area",
	SeriesSymbol_false: "False",
	SeriesSymbol_true: "True",
	SeriesSymbol_radius: "Radius",
	SeriesSymbol_rose_type: "Rose Type",
	SeriesSymbol_pad_angle: "Pad Angle",
	SeriesSymbol_start_angle: "Start Angle",
	SeriesSymbol_avoid_label_overlap: "Avoid Label Overlap",
	SeriesSymbol_cursor: "Cursor",
	SeriesSymbol_percent_precision: "Percent Precision",
	SeriesSymbol_show_empty_circle: "Show Empty Circle",
	SeriesSymbol_still_show_zero_sum: "Still Show Zero Sum",
	SeriesSymbol_behaviour: "Behaviour",
	SeriesSymbol_selected_offset: "Selected Offset",
	SeriesSymbol_events: "Events",
	SeriesSymbol_pie_symbol: "Pie Symbol",
	SeriesSymbol_name: "Name",
	SeriesSymbol_line: "Line",
	SeriesSymbol_bar: "Bar",
	SeriesSymbol_pie: "Pie",
	SeriesSymbol_type: "Type",
	SeriesSymbol_delay: "Delay",
	SeriesSymbol_delay_update: "Delay Update",
	SeriesSymbol_duration: "Duration",
	SeriesSymbol_duration_update: "Duration Update",
	SeriesSymbol_easing_linear: "Linear",
	SeriesSymbol_easing_quadratic_in: "Quadratic In",
	SeriesSymbol_easing_quadratic_out: "Quadratic Out",
	SeriesSymbol_easing_quadratic_in_out: "Quadratic In Out",
	SeriesSymbol_easing_cubic_in: "Cubic In",
	SeriesSymbol_easing_cubic_out: "Cubic Out",
	SeriesSymbol_easing_cubic_in_out: "Cubic In Out",
	SeriesSymbol_easing_quartic_in: "Quartic In",
	SeriesSymbol_easing_quartic_out: "Quartic Out",
	SeriesSymbol_easing_quartic_in_out: "Quartic In Out",
	SeriesSymbol_easing_quintic_in: "Quintic In",
	SeriesSymbol_easing_quintic_out: "Quintic Out",
	SeriesSymbol_easing_quintic_in_out: "Quintic In Out",
	SeriesSymbol_easing_sinusoidal_in: "Sinusoidal In",
	SeriesSymbol_easing_sinusoidal_out: "Sinusoidal Out",
	SeriesSymbol_easing_sinusoidal_in_out: "Sinusoidal In Out",
	SeriesSymbol_easing_exponential_in: "Exponential In",
	SeriesSymbol_easing_exponential_out: "Exponential Out",
	SeriesSymbol_easing_exponential_in_out: "Exponential In Out",
	SeriesSymbol_easing_circular_in: "Circular In",
	SeriesSymbol_easing_circular_out: "Circular Out",
	SeriesSymbol_easing_circular_in_out: "Circular In Out",
	SeriesSymbol_easing_elastic_in: "Elastic In",
	SeriesSymbol_easing_elastic_out: "Elastic Out",
	SeriesSymbol_easing_elastic_in_out: "Elastic In Out",
	SeriesSymbol_easing_back_in: "Back In",
	SeriesSymbol_easing_back_out: "Back Out",
	SeriesSymbol_easing_back_in_out: "Back In Out",
	SeriesSymbol_easing_bounce_in: "Bounce In",
	SeriesSymbol_easing_bounce_out: "Bounce Out",
	SeriesSymbol_easing_bounce_in_out: "Bounce In Out",
	SeriesSymbol_easing: "Easing",
	SeriesSymbol_easing_update: "Easing Update",
	SeriesSymbol_threshold: "Threshold",
	SeriesSymbol_toggle_universal_transition: "Toggle Universal Transition",
	SeriesSymbol_enabled: "Enabled",
	SeriesSymbol_clone: "Clone",
	SeriesSymbol_split: "Split",
	SeriesSymbol_divide_shape: "Divide Shape",
	SeriesSymbol_universal_transition: "Universal Transition",
	SeriesSymbol_animation: "Animation",
	SeriesSymbol_data: "Data",
	SeriesSymbol_series: "Series",
	SeriesSymbol_colour_scheme: "Colour Scheme",
	SeriesSymbol_interactive: "Interactive",
	SeriesSymbol_interpolate: "Interpolate",
	SeriesSymbol_average: "Average",
	SeriesSymbol_max: "Max",
	SeriesSymbol_min: "Min",
	SeriesSymbol_minmax: "Minmax",
	SeriesSymbol_lttb: "LTTB",
	SeriesSymbol_sum: "Sum",
	SeriesSymbol_none: "None",
	SeriesSymbol_sampling: "Sampling",
	SeriesSymbol_x: "X",
	SeriesSymbol_y: "Y",
	SeriesSymbol_smoothing: "Smoothing",
	SeriesSymbol_z_index: "Z Index",
	SeriesSymbol_lighter: "Lighter",
	SeriesSymbol_source_over: "Source-Over",
	SeriesSymbol_blend_mode: "Blend Mode",
	SeriesSymbol_hover_layer_threshold: "Hover Layer Threshold",
	SeriesSymbol_rich_text_inherits_plain_label: "Rich Text Inherits Plain Label",
	SeriesSymbol_use_utc: "Use UTC",
	SeriesSymbol_behaviour_advanced: "Behaviour (Advanced) ",
	SeriesSymbol_stack: "Stack",
	SeriesSymbol_all: "All",
	SeriesSymbol_negative: "Negative",
	SeriesSymbol_positive: "Positive",
	SeriesSymbol_same_sign: "Same Sign",
	SeriesSymbol_stack_mode: "Stack Mode",
	SeriesSymbol_order_series_asc: "Series Ascending",
	SeriesSymbol_order_series_desc: "Series Descending",
	SeriesSymbol_stack_order: "Stack Order",
	SeriesSymbol_behaviour_stack: "Behaviour (Stack)",
	SeriesSymbol_height: "Height",
	SeriesSymbol_width: "Width",
	SeriesSymbol_bottom: "Bottom",
	SeriesSymbol_left: "Left",
	SeriesSymbol_right: "Right",
	SeriesSymbol_top: "Top",
	SeriesSymbol_coordinates: "Coordinates",
	SeriesSymbol_cartesian_2d: "Cartesian 2D",
	SeriesSymbol_polar: "Polar",
	SeriesSymbol_coordinate_system: "Coordinate System",
	SeriesSymbol_polar_index: "Polar Index",
	SeriesSymbol_x_axis_index: "X Axis Index",
	SeriesSymbol_y_axis_index: "Y Axis Index",
	SeriesSymbol_coordinates_advanced: "Coordinates (Advanced)",
	SeriesSymbol_calendar_id: "Calendar ID",
	SeriesSymbol_calendar_index: "Calendar Index",
	SeriesSymbol_geo_io: "Geo IO",
	SeriesSymbol_geo_index: "Geo Index",
	SeriesSymbol_matrix_io: "Matrix IO",
	SeriesSymbol_matrix_index: "Matrix Index",
	SeriesSymbol_coordinates_assignment: "Coordinates (Assignment)",
	SeriesSymbol_end_label_symbol: "End Label Symbol",
	SeriesSymbol_fill_symbol: "Fill Symbol",
	SeriesSymbol_label_symbol: "Label Symbol",
	SeriesSymbol_label_stroke_symbol: "Label Stroke Symbol",
	SeriesSymbol_point_symbol: "Point Symbol",
	SeriesSymbol_stroke_symbol: "Stroke Symbol",
	SeriesSymbol_onblur: "Onblur",
	SeriesSymbol_self: "Self",
	SeriesSymbol_focus: "Focus",
	SeriesSymbol_highlight: "Highlight",
	SeriesSymbol_scale: "Scale",
	SeriesSymbol_global: "Global",
	SeriesSymbol_blur_scope: "Blur Scope",
	SeriesSymbol_onhover: "Onhover",
	SeriesSymbol_onselect: "Onselect",
	SeriesSymbol_tooltip: "Tooltip",
	SeriesSymbol_tooltip_symbol: "Tooltip Symbol",
	SeriesSymbol_large: "Large",
	SeriesSymbol_large_threshold: "Large Threshold",
	SeriesSymbol_progressive: "Progressive",
	SeriesSymbol_mod: "Mod",
	SeriesSymbol_sequential: "Sequential",
	SeriesSymbol_progressive_chunk_mode: "Progressive Chunk Mode",
	SeriesSymbol_progressive_threshold: "Progressive Threshold",
	SeriesSymbol_optimisation: "Optimisation",
	SeriesSymbol_series_symbol: "Series Symbol",
	
	DatavisSuite_graph: "Graph",
	DatavisSuite_series: "Series",
	DatavisSuite_script_manager: "ScriptManager",
	DatavisSuite_view: "View",
	DatavisSuite_toast_added_chart_to_graph: "Added chart to graph.",
	DatavisSuite_tooltip_add_graph: "Add Graph",
	DatavisSuite_tooltip_add_legend: "Add Legend",
	DatavisSuite_tooltip_add_overlay_text: "Add Overlay Text",
	DatavisSuite_new_graph: "New Graph",
	DatavisSuite_tooltip_delete_graph: "Delete Graph",
	DatavisSuite_toast_invalid_data_series: "The data series you have selected is not valid.",
	DatavisSuite_attached_series: "Attached Series",
	DatavisSuite_background_colour: "Background Colour",
	DatavisSuite_default_colours: "Default Colours",
	DatavisSuite_x_axis_symbol: "X Axis Symbol",
	DatavisSuite_y_axis_symbol: "Y Axis Symbol",
	DatavisSuite_polar_axis_symbol: "Polar Axis Symbol",
	DatavisSuite_axis_symbols: "Axis Symbols",
	DatavisSuite_text_symbol: "Text Symbol",
	DatavisSuite_title_symbol: "Title Symbol",
	DatavisSuite_tooltip_symbol: "Tooltip Symbol",
	DatavisSuite_visual_map: "Visual Map",
	DatavisSuite_edit: "Edit",
	DatavisSuite_tooltip_modify_graph: "Modify Graph",
	DatavisSuite_loading: "Loading ..",
	DatavisSuite_edit_graph: "Edit Graph",
	DatavisSuite_new_series: "New Series",
	DatavisSuite_tooltip_create_new_series: "Create New Series",
	DatavisSuite_confirm_delete_series: "Are you sure you wish to delete £1£?",
	DatavisSuite_tooltip_delete_series: "Delete Series",
	DatavisSuite_tooltip_modify_series: "Modify Series",
	DatavisSuite_series_range: "Series Range",
	DatavisSuite_toast_cleared_range: "Cleared selected series range.",
	DatavisSuite_clear_range: "Clear Range",
	DatavisSuite_select_series_range: "Select Series Range",
	DatavisSuite_toast_range_set: "New series range set.",
	DatavisSuite_set_series_range: "Set Series Range",
	DatavisSuite_data_series: "Data Series",
	DatavisSuite_script_manager_window_name: "ScriptManager (Datavis Suite)",
	
	//Hierarchy
	Hierarchy_search_for_item: "Search for item ...",
	
	//NodeEditor
	//Forse
	Forse_category_config: "Config",
	Forse_category_custom: "Custom",
	Forse_category_parameters: "Parameters",
	Forse_category_conditionals: "Conditionals",
	Forse_category_functions: "Functions",
	Forse_category_loops: "Loops",
	Forse_category_variables: "Variables",
	Forse_category_variables_casting: "Variables (Casting)",
	Forse_category_variables_expressions: "Variables (Expressions)",
	Forse_node_comment: "Comment",
	Forse_node_category: "Node Category",
	Forse_param_category: "Category",
	Forse_node_name: "Node Name",
	Forse_param_name: "Name",
	Forse_node_output_type: "Node Output Type",
	Forse_param_type: "Type",
	Forse_node_input: "Input (Parameter)",
	Forse_node_output: "Output (Return)",
	Forse_param_result: "Result",
	
	Forse_node_is_equal: "Is Equal",
	Forse_node_is_strictly_equal: "Is Strictly Equal",
	Forse_node_is_not_equal: "Is Not Equal",
	Forse_node_is_not_strictly_equal: "Is Not Strictly Equal",
	Forse_node_geq: "Greater or Equal Than",
	Forse_node_greater_than: "Greater Than",
	Forse_node_leq: "Less Than or Equal To",
	Forse_node_less_than: "Less Than",
	Forse_node_if_then: "If Then",
	Forse_node_false: "False",
	Forse_node_true: "True",
	Forse_node_null: "Null",
	Forse_node_undefined: "Undefined",
	Forse_node_and: "AND",
	Forse_node_not: "NOT",
	Forse_node_or: "OR",
	Forse_node_xor: "XOR",
	Forse_param_arg0_variable: "arg0_variable",
	Forse_param_arg1_variable: "arg1_variable",
	Forse_param_arg0_boolean: "arg0_boolean",
	Forse_value_true: "True",
	Forse_value_false: "False",
	Forse_value_null: "null",
	Forse_value_undefined: "undefined",
	
	Forse_node_call_function: "Call Function",
	Forse_param_function_key: "arg0_function_key",
	Forse_param_arguments_array: "arg1_arguments_array",
	Forse_display_run_global: "Run: global.£1£",
	Forse_node_call_function_preview: "Call Function (Preview)",
	Forse_node_call_method: "Call Method",
	Forse_param_method_key: "arg1_method_key",
	Forse_display_run_class_method: "Run Class Method: £1£",
	Forse_node_call_method_preview: "Call Method (Preview)",
	Forse_node_get_class_field: "Get Class Field",
	Forse_param_field_key: "arg1_field_key",
	Forse_display_field_access: ".£1£: £2£",
	Forse_node_set_class_field: "Set Class Field",
	Forse_node_log_error: "(Log) ERROR",
	Forse_display_logged_error: "Logged Error",
	Forse_node_log_info: "(Log) INFO",
	Forse_display_logged_info: "Logged Info",
	Forse_node_log_warn: "(Log) WARN",
	Forse_display_logged_warning: "Logged Warning",
	Forse_node_run_script: "Run Script",
	Forse_param_script: "arg0_script",
	Forse_display_run_script: "Run: £1£",
	
	Forse_node_for_loop: "For Loop",
	Forse_param_times: "arg0_times",
	Forse_display_iterate_x: "Iterate £1£x",
	Forse_node_get_obj_iter_key: "Get Obj.Iter. Key",
	Forse_param_object_iteration: "arg0_object_iteration",
	Forse_display_dot_key: ".£1£",
	Forse_node_get_obj_iter_value: "Get Obj.Iter. Value",
	Forse_display_iteration_value: "Iteration Value",
	Forse_node_iterate_over_object: "Iterate over Object",
	Forse_param_object: "arg0_object",
	Forse_display_key: "Key: £1£",
	Forse_display_empty_object: "Empty Object",
	Forse_node_set_timeout: "Set Timeout",
	Forse_param_timeout: "arg0_timeout",
	Forse_param_value: "arg1_value",
	Forse_display_wait_ms: "Wait £1£ms",
	
	Forse_param_arg0_key: "arg0_key",
	Forse_display_variable_value: "£1£: £2£",
	Forse_node_set_any: "Set Any",
	Forse_param_arg1_value: "arg1_value",
	Forse_node_set_string_array: "Set String Array",
	Forse_display_elements: "£1£: £2£ Elements",
	Forse_node_set_number_array: "Set Number Array",
	Forse_node_set_boolean: "Set Boolean",
	Forse_node_set_number: "Set Number",
	Forse_node_set_string: "Set String",
	Forse_node_set_array: "Set Array",
	Forse_node_set_null: "Set Null",
	Forse_node_set_object: "Set Object",
	Forse_node_get_any: "Get Any",
	Forse_node_get_string_array: "Get String Array",
	Forse_node_get_number_array: "Get Number Array",
	Forse_node_get_boolean: "Get Boolean",
	Forse_node_get_number: "Get Number",
	Forse_node_get_string: "Get String",
	Forse_node_get_array: "Get Array",
	Forse_node_get_null: "Get Null",
	Forse_node_get_object: "Get Object",
	Forse_node_get_global: "Get Global",
	
	Forse_node_convert_to_any: "Convert to Any",
	Forse_display_type_any: "Type: any",
	Forse_node_convert_to_array: "Convert to Array",
	Forse_display_any_array_len: "any[£1£]",
	Forse_node_convert_to_string_array: "Convert to String Array",
	Forse_display_string_array_len: "string[£1£]",
	Forse_node_convert_to_number_array: "Convert to Number Array",
	Forse_display_number_array_len: "number[£1£]",
	Forse_node_convert_to_boolean: "Convert to Boolean",
	Forse_display_boolean_value: "boolean: £1£",
	Forse_node_convert_to_number: "Convert to Number",
	Forse_node_convert_to_script: "Convert to Script",
	Forse_param_arg0_file_path: "arg0_file_path",
	Forse_node_convert_to_string: "Convert to String",
	
	Forse_node_array_concat: "Array Concat",
	Forse_param_arg0_array: "arg0_array",
	Forse_param_arg1_array: "arg1_array",
	Forse_node_array_indexof: "Array Indexof",
	Forse_param_arg1_element: "arg1_element",
	Forse_node_array_length: "Array Length",
	Forse_node_array_pop: "Array Pop",
	Forse_node_array_push: "Array Push",
	Forse_display_pushed_element: "Pushed £1£",
	Forse_node_array_reverse: "Array Reverse",
	Forse_node_array_shift: "Array Shift",
	Forse_display_shifted_element: "Shifted: £1£",
	Forse_node_array_splice: "Array Splice",
	Forse_param_arg1_index: "arg1_index",
	Forse_param_arg2_how_many: "arg2_how_many",
	Forse_display_spliced_items: "Spliced £1£ items",
	Forse_node_array_unshift: "Array Unshift",
	Forse_display_unshifted_element: "Unshifted £1£",
	Forse_node_join_array: "Join Array",
	Forse_param_arg1_separator: "arg1_separator",
	Forse_display_quoted_string: "\"£1£\"",
	Forse_node_split_string: "Split String",
	Forse_param_arg0_string: "arg0_string",
	Forse_display_elements_count: "£1£ Elements",
	Forse_node_merge_objects: "Merge Objects",
	Forse_param_arg0_object: "arg0_object",
	Forse_param_arg1_object: "arg1_object",
	Forse_display_merged_object: "Merged Object",
	Forse_node_get_object_keys: "Get Object Keys",
	Forse_display_keys_count: "£1£ Keys",
	Forse_node_get_object_values: "Get Object Values",
	Forse_display_values_count: "£1£ Values",
	Forse_node_add_numbers: "Add Numbers",
	Forse_param_arg0_number: "arg0_number",
	Forse_param_arg1_number: "arg1_number",
	Forse_node_exponentiate_numbers: "Exponentiate Numbers",
	Forse_node_modulo: "Modulo",
	Forse_node_multiply_numbers: "Multiply Numbers",
	Forse_node_divide_numbers: "Divide Numbers",
	Forse_node_subtract_numbers: "Subtract Numbers",
	Forse_node_add_strings: "Add Strings",
	Forse_param_arg1_string: "arg1_string",
	Forse_node_ends_with: "Ends With",
	Forse_param_arg1_search: "arg1_search",
	Forse_node_matches: "Matches",
	Forse_param_arg1_regex: "arg1_regex",
	Forse_display_matches_count: "£1£ Matches",
	Forse_node_replace: "Replace",
	Forse_param_arg1_pattern: "arg1_pattern",
	Forse_param_arg2_replacement: "arg2_replacement",
	Forse_node_replace_all: "Replace All",
	Forse_node_string_length: "String Length",
	Forse_node_starts_with: "Starts With",
	
	NodeEditor_toast_custom_node_deleted: "Custom Node Deleted.",
	NodeEditor_param_default: "Param £1£",
	NodeEditor_new_custom_node: "New Custom Node",
	NodeEditor_toast_error_missing_output: "Custom Node must have an 'Output' node.",
	NodeEditor_updated: "Updated",
	NodeEditor_created: "Created",
	NodeEditor_toast_custom_node_success: "Custom Node '£1£' £2£.",
	NodeEditor_update_custom_node: "Update Custom Node",
	NodeEditor_save_custom_node: "Save Custom Node",
	NodeEditor_edit_node: "Edit £1£",
	NodeEditor_create_custom_node: "Create Custom Node",
	
	NodeEditor_category_uncategorised: "Uncategorised",
	NodeEditor_category_expressions: "Expressions",
	NodeEditor_category_filters: "Filters",
	NodeEditor_category_io: "I/O",
	NodeEditor_category_all: "All",
	NodeEditor_comment_placeholder: "Enter comment...",
	NodeEditor_button_place_comment: "Place Comment",
	NodeEditor_window_add_comment: "Add Comment",
	NodeEditor_context_edit_node: "<icon>edit</icon> Edit Node",
	NodeEditor_context_delete_node: "<icon>delete</icon> Delete Node",
	NodeEditor_button_create_custom_node: "<icon>add_circle</icon> Create Custom Node",
	NodeEditor_window_toolbox: "Toolbox",
	
	//ScriptManager
	ScriptManager_are_you_sure_clear_console: "Are you sure you want to clear the current console?",
	ScriptManager_clear_blockly_on_error: "Clear Blockly on error",
	ScriptManager_clear_console: "Clear Console",
	ScriptManager_console: "Console",
	ScriptManager_could_not_load_settings: "Could not load non-ScriptManager settings.",
	ScriptManager_display_load_errors: "Display load errors",
	ScriptManager_editor_theme: "Editor Theme",
	ScriptManager_enter_console_command: "Enter console command ...",
	ScriptManager_error_compatibility: "Are you sure this file is £1£ compatible? Blockly has been disabled, and the file is only editable via CodeMirror.",
	ScriptManager_error_loading_settings: "Error loading settings",
	ScriptManager_error_reading_file: "Error Reading File",
	ScriptManager_help: "Help",
	ScriptManager_help_menu: "Help Menu:",
	ScriptManager_hide_blockly: "Hide Blockly",
	ScriptManager_hide_show_blockly: "Hide/show Blockly workspace on error",
	ScriptManager_load_settings: "Load Settings",
	ScriptManager_monaco_theme: "Code Theme",
	ScriptManager_no_project: "No Project",
	ScriptManager_none: "None",
	ScriptManager_note: "Note:",
	ScriptManager_object_to_be_logged: "Object to be logged exceeds £1£k characters. Are you sure you want to view it?",
	ScriptManager_keybinds: "Keybinds",
	ScriptManager_prints_help_information: "Prints help information.",
	ScriptManager_run: "Run",
	ScriptManager_run_current_file: "Run Current File",
	ScriptManager_run_settings: "Run Settings:",
	ScriptManager_save_settings: "Save Settings",
	ScriptManager_saved_settings: "Saved settings to £1£!",
	ScriptManager_send: "Send",
	ScriptManager_settings: "Settings",
	ScriptManager_show_blockly: "Show Blockly",
	ScriptManager_stack_trace: "Stack Trace:",
	ScriptManager_theme_default: "Default",
	ScriptManager_theme_light: "Light",
	ScriptManager_trust_warning: "Make sure you trust the code you are about to run before executing it.",
	ScriptManager_view: "View",
	ScriptManager_view_file_explorer: "View File Explorer",
	ScriptManager_view_settings: "View Settings:",
	
	//Button
	Button_confirm: "Confirm",
	
	//DateLength
	DateLength_days: "Days",
	DateLength_months: "Months",
	DateLength_years: "Years",
	
	//File
	File_already_exists: "File already exists. Do you want to overwrite it?",
	File_can_only_select_files: "You can only select files.",
	File_can_only_select_folders: "You can only select folders.",
	File_can_only_select_one_file: "You can only select 1 file/folder path.",
	File_cancel: "Cancel",
	File_confirm: "Confirm",
	File_error_saving_file: "Error Saving File",
	File_error_saving_file_desc: "Error saving file: £1£",
	File_must_select_valid_path: "You must select a valid file/folder path.",
	File_open_file: "Open File",
	File_open_files: "Open Files",
	File_open_folder: "Open Folder",
	File_open_folders: "Open Folders",
	File_save_file: "Save File",
	File_save_file_as: "Save file as ...",
	File_select_file: "Select File",
	File_selected_files: "Selected £1£ file(s).",
	File_successfully_saved_file: "Successfully saved file in: £1£",
	
	//Interface
	Interface_folder: "Folder",
	
	//List
	List_delete_item: "Delete Item",
	List_error_max_items_reached: "The length of the current list cannot exceed £1£ element(s).",
	List_error_min_items_reached: "The length of the current list cannot go below £1£ element(s).",
	List_info_edit_item: "Edit Item",
	List_insert_item_after: "Insert Item After",
	List_insert_item_before: "Insert Item Before",
	List_shift: "Shift",
	List_shift_left: "Shift Left",
	List_shift_right: "Shift Right",
	
	//SearchSelect
	SearchSelect_no_elements_found: "No elements available to search for.",
	SearchSelect_search_filter: "Search Filter",
	
	//UndoRedo
	UndoRedo_actions_map: "Actions Map",
	UndoRedo_branch_at_node: "Branch At Node",
	UndoRedo_coords_display: "X: £1£, Y: £2£ | Scale: £3£",
	UndoRedo_initialisation: "S. Init",
	UndoRedo_jump_to: "Jump To",
	UndoRedo_name: "Name:",
	UndoRedo_split_from_timeline: "Split From Timeline",
	UndoRedo_timeline: "Timeline",
	UndoRedo_timeline_view: "Timeline View",
	UndoRedo_unlisted: "Unlisted",
	
	//Sort filter
	UndoRedo_sorting_filter: "Sorting Filter",
	UndoRedo_sort_timelines: "Sort Timelines:",
	
	//Sort filters
	UndoRedo_alphabetical_ascending: "Alphabetical (A-Z)",
	UndoRedo_alphabetical_descending: "Alphabetical (Z-A)",
	UndoRedo_chronological_ascending: "Chronological (Ascending)",
	UndoRedo_chronological_descending: "Chronological (Descending)",
	UndoRedo_last_modified: "Last Modified",
	UndoRedo_least_actions: "Least Actions",
	UndoRedo_most_actions: "Most Actions",
	
	//WYSIWYG
	WYSIWYG_align_centre: "Align Centre",
	WYSIWYG_align_left: "Align Left",
	WYSIWYG_align_right: "Align Right",
	WYSIWYG_bold: "Bold",
	WYSIWYG_done: "Done",
	WYSIWYG_indent: "Indent",
	WYSIWYG_insert_link: "Insert Link",
	WYSIWYG_insert_ordered_list: "Insert ordered list",
	WYSIWYG_insert_unordered_list: "Insert unordered list",
	WYSIWYG_italic: "Italic",
	WYSIWYG_justify: "Justify",
	WYSIWYG_open_in_new_tab: "Open in New Tab?",
	WYSIWYG_outdent: "Outdent",
	WYSIWYG_redo: "Redo",
	WYSIWYG_remove_format: "Remove format",
	WYSIWYG_show_html_code: "Show HTML Code",
	WYSIWYG_strikethrough: "Strikethrough",
	WYSIWYG_underline: "Underline",
	WYSIWYG_undo: "Undo",
	WYSIWYG_unlink: "Unlink",
	
	//ve.Feature
	//Confirm
	Confirm_confirm: "Confirm",
	Confirm_no: "No",
	Confirm_yes: "Yes",
	
	//DE (German)
	
	//ve.Component
	//FileExplorer
	FileExplorer_are_you_sure_delete_de: "Sind Sie sicher, dass Sie die folgenden Dateien löschen wollen?<br><br>£1£<br><br>Diese Aktion kann nicht rückgängig gemacht werden!",
	FileExplorer_are_you_sure_copy_paste_de: "Sind Sie sicher, dass Sie £1£ Datei(en) nach £2£ kopieren/einfügen wollen?",
	FileExplorer_are_you_sure_load_de: "Sind Sie sicher, dass Sie £1£ laden wollen?",
	FileExplorer_back_de: "Zurück",
	FileExplorer_cannot_create_unnamed_folder_de: "Sie können keinen Ordner ohne Namen erstellen.",
	FileExplorer_clear_clipboard_de: "Zwischenablage leeren",
	FileExplorer_clipboard_de: "Zwischenablage",
	FileExplorer_clipboard_is_empty_de: "Zwischenablage ist leer.",
	FileExplorer_create_a_new_file_de: "Neue Datei erstellen:",
	FileExplorer_create_new_file_de: "Neue Datei erstellen",
	FileExplorer_create_new_folder_de: "Neuen Ordner erstellen",
	FileExplorer_create_a_new_folder_de: "Neuen Ordner erstellen:",
	FileExplorer_created_empty_text_file_de: "Leere Textdatei erstellt unter: £1£",
	FileExplorer_cut_paste_files_de: "£1£ Dateien ausschneiden/einfügen",
	FileExplorer_confirm_de: "Bestätigen",
	FileExplorer_copied_elements_to_clipboard_de: "£1£ Elemente in die Zwischenablage kopiert.",
	FileExplorer_copy_selected_de: "Ausgewählte kopieren",
	FileExplorer_delete_files_de: "£1£ Dateien löschen",
	FileExplorer_do_you_want_to_overwrite_file_de: "Datei existiert bereits. Möchten Sie sie überschreiben?",
	FileExplorer_elements_selected_de: "£1£ Elemente ausgewählt",
	FileExplorer_error_load_de: "Fehler beim Laden der Datei £1£: £2£",
	FileExplorer_error_load_save_file_de: "Fehler beim Laden der Speicherdatei",
	FileExplorer_load_save_file_de: "Speicherdatei laden",
	FileExplorer_loaded_save_file_de: "Speicherdatei £1£ geladen",
	FileExplorer_move_files_de: "£1£ Dateien verschieben",
	FileExplorer_paste_clipboard_de: "Zwischenablage einfügen",
	FileExplorer_paste_files_de: "£1£ Dateien einfügen",
	FileExplorer_rename_de: "Umbenennen",
	FileExplorer_save_file_de: "Datei speichern",
	FileExplorer_save_file_as_de: "Datei speichern unter:",
	FileExplorer_select_de: "Auswählen",
	FileExplorer_specified_file_path_already_exists_de: "Der angegebene Pfad existiert bereits als Datei! Löschen Sie sie zuerst, bevor Sie eine neue Datei mit demselben Namen erstellen.",
	FileExplorer_successfully_saved_file_as_de: "Datei erfolgreich gespeichert unter: £1£",
	
	//FileExplorer (File Operations)
	FileExplorer_copying_files_to_de: "Kopiere £1£ Datei(en) nach £2£",
	FileExplorer_copying_to_de: "Kopiere £1£ nach £2£",
	FileExplorer_deleting_files_de: "Lösche £1£ Datei(en)",
	FileExplorer_deleting_path_de: "Lösche £1£",
	FileExplorer_done_de: "Fertig",
	FileExplorer_error_could_not_be_renamed_de: "FEHLER: £1£ konnte nicht umbenannt werden: £2£",
	FileExplorer_eta_remaining_de: "£1£% - £2£ verbleibend",
	FileExplorer_finished_moving_files_de: "Verschieben der Dateien abgeschlossen",
	FileExplorer_of_progress_de: "(£1£ von £2£)",
	FileExplorer_moved_files_de: "Verschieben von £1£ Datei(en) nach £2£ abgeschlossen",
	FileExplorer_rename_file_de: "Datei umbenennen",
	FileExplorer_rename_file_to_de: "Datei £1£ umbenennen in:",
	
	//Hierarchy
	Hierarchy_search_for_item_de: "Suche nach Element ...",
	
	//ScriptManager
	ScriptManager_are_you_sure_clear_console_de: "Sind Sie sicher, dass Sie die aktuelle Konsole leeren wollen?",
	ScriptManager_clear_blockly_on_error_de: "Blockly bei Fehler leeren",
	ScriptManager_clear_console_de: "Konsole leeren",
	ScriptManager_codemirror_theme_de: "Codemirror-Theme",
	ScriptManager_console_de: "Konsole",
	ScriptManager_could_not_load_settings_de: "Nicht-ScriptManager-Einstellungen konnten nicht geladen werden.",
	ScriptManager_display_load_errors_de: "Ladefehler anzeigen",
	ScriptManager_editor_theme_de: "Editor-Theme",
	ScriptManager_enter_console_command_de: "Konsolenbefehl eingeben ...",
	ScriptManager_error_compatibility_de: "Sind Sie sicher, dass diese Datei £1£-kompatibel ist? Blockly wurde deaktiviert und die Datei ist nur über CodeMirror bearbeitbar.",
	ScriptManager_error_loading_settings_de: "Fehler beim Laden der Einstellungen",
	ScriptManager_error_reading_file_de: "Fehler beim Lesen der Datei",
	ScriptManager_help_de: "Hilfe",
	ScriptManager_help_menu_de: "Hilfemenü:",
	ScriptManager_hide_blockly_de: "Blockly verbergen",
	ScriptManager_hide_show_blockly_de: "Blockly-Arbeitsbereich bei Fehler verbergen/anzeigen",
	ScriptManager_load_settings_de: "Einstellungen laden",
	ScriptManager_none_de: "Keine",
	ScriptManager_note_de: "Hinweis:",
	ScriptManager_keybinds_de: "Tastenbelegungen",
	ScriptManager_prints_help_information_de: "Gibt Hilfeinformationen aus.",
	ScriptManager_run_de: "Ausführen",
	ScriptManager_run_current_file_de: "Aktuelle Datei ausführen",
	ScriptManager_run_settings_de: "Ausführungseinstellungen:",
	ScriptManager_save_settings_de: "Einstellungen speichern",
	ScriptManager_saved_settings_de: "Einstellungen in £1£ gespeichert!",
	ScriptManager_send_de: "Senden",
	ScriptManager_settings_de: "Einstellungen",
	ScriptManager_show_blockly_de: "Blockly anzeigen",
	ScriptManager_stack_trace_de: "Stack Trace:",
	ScriptManager_theme_default_de: "Standard",
	ScriptManager_theme_light_de: "Hell",
	ScriptManager_trust_warning_de: "Stellen Sie sicher, dass Sie dem Code vertrauen, bevor Sie ihn ausführen.",
	ScriptManager_view_de: "Ansicht",
	ScriptManager_view_file_explorer_de: "Dateimanager anzeigen",
	ScriptManager_view_settings_de: "Ansichtseinstellungen",
	
	//SearchSelect
	SearchSelect_no_elements_found_de: "Keine Elemente zum Suchen verfügbar.",
	SearchSelect_search_filter_de: "Suchfilter",
	
	//Button
	Button_confirm_de: "Bestätigen",
	
	//DateLength
	DateLength_days_de: "Tage",
	DateLength_months_de: "Monate",
	DateLength_years_de: "Jahre",
	
	//File
	File_already_exists_de: "Datei existiert bereits. Möchten Sie sie überschreiben?",
	File_can_only_select_files_de: "Sie können nur Dateien auswählen.",
	File_can_only_select_folders_de: "Sie können nur Ordner auswählen.",
	File_can_only_select_one_file_de: "Sie können nur 1 Datei/Ordnerpfad auswählen.",
	File_cancel_de: "Abbrechen",
	File_confirm_de: "Bestätigen",
	File_error_saving_file_de: "Fehler beim Speichern der Datei",
	File_error_saving_file_desc_de: "Fehler beim Speichern der Datei: £1£",
	File_must_select_valid_path_de: "Sie müssen einen gültigen Datei-/Ordnerpfad auswählen.",
	File_open_file_de: "Datei öffnen",
	File_open_files_de: "Dateien öffnen",
	File_open_folder_de: "Ordner öffnen",
	File_open_folders_de: "Ordner öffnen",
	File_save_file_de: "Datei speichern",
	File_save_file_as_de: "Datei speichern unter ...",
	File_select_file_de: "Datei auswählen",
	File_selected_files_de: "£1£ Datei(en) ausgewählt.",
	File_successfully_saved_file_de: "Datei erfolgreich gespeichert in: £1£",
	
	//Interface
	Interface_folder_de: "Ordner",
	
	//List
	List_delete_item_de: "Element löschen",
	List_error_max_items_reached_de: "Die Länge der aktuellen Liste darf £1£ Element(e) nicht überschreiten.",
	List_error_min_items_reached_de: "Die Länge der aktuellen Liste darf £1£ Element(e) nicht unterschreiten.",
	List_info_edit_item_de: "Element bearbeiten",
	List_insert_item_after_de: "Element danach einfügen",
	List_insert_item_before_de: "Element davor einfügen",
	List_shift_de: "Verschieben",
	List_shift_left_de: "Nach links verschieben",
	List_shift_right_de: "Nach rechts verschieben",
	
	//UndoRedo
	UndoRedo_actions_map_de: "Aktionskarte",
	UndoRedo_branch_at_node_de: "Bei Knoten verzweigen",
	UndoRedo_coords_display_de: "X: £1£, Y: £2£ | Skalierung: £3£",
	UndoRedo_initialisation_de: "S. Init",
	UndoRedo_jump_to_de: "Springe zu",
	UndoRedo_name_de: "Name:",
	UndoRedo_split_from_timeline_de: "Von Zeitlinie abspalten",
	UndoRedo_timeline_de: "Zeitlinie",
	UndoRedo_timeline_view_de: "Zeitlinienansicht",
	UndoRedo_unlisted_de: "Ungelistet",
	
	//Sort filter
	UndoRedo_sorting_filter_de: "Sortierfilter",
	UndoRedo_sort_timelines_de: "Zeitlinien sortieren:",
	
	//Sort filters
	UndoRedo_alphabetical_ascending_de: "Alphabetisch (A-Z)",
	UndoRedo_alphabetical_descending_de: "Alphabetisch (Z-A)",
	UndoRedo_chronological_ascending_de: "Chronologisch (Aufsteigend)",
	UndoRedo_chronological_descending_de: "Chronologisch (Absteigend)",
	UndoRedo_last_modified_de: "Zuletzt geändert",
	UndoRedo_least_actions_de: "Wenigste Aktionen",
	UndoRedo_most_actions_de: "Meiste Aktionen",
	
	//WYSIWYG
	WYSIWYG_align_centre_de: "Zentriert ausrichten",
	WYSIWYG_align_left_de: "Linksbündig ausrichten",
	WYSIWYG_align_right_de: "Rechtsbündig ausrichten",
	WYSIWYG_bold_de: "Fett",
	WYSIWYG_done_de: "Fertig",
	WYSIWYG_indent_de: "Einrücken",
	WYSIWYG_insert_link_de: "Link einfügen",
	WYSIWYG_insert_ordered_list_de: "Nummerierte Liste einfügen",
	WYSIWYG_insert_unordered_list_de: "Aufzählung einfügen",
	WYSIWYG_italic_de: "Kursiv",
	WYSIWYG_justify_de: "Blocksatz",
	WYSIWYG_open_in_new_tab_de: "In neuem Tab öffnen?",
	WYSIWYG_outdent_de: "Ausrücken",
	WYSIWYG_redo_de: "Wiederholen",
	WYSIWYG_remove_format_de: "Formatierung entfernen",
	WYSIWYG_show_html_code_de: "HTML-Code anzeigen",
	WYSIWYG_strikethrough_de: "Durchgestrichen",
	WYSIWYG_underline_de: "Unterstrichen",
	WYSIWYG_undo_de: "Rückgängig",
	WYSIWYG_unlink_de: "Link entfernen",
	
	//ve.Feature
	//Confirm
	Confirm_confirm_de: "Bestätigen",
	Confirm_no_de: "Nein",
	Confirm_yes_de: "Ja",
	
	//FR (French)
	
	//ve.Component
	//FileExplorer
	FileExplorer_are_you_sure_delete_fr: "Êtes-vous sûr de vouloir supprimer les fichiers suivants ?<br><br>£1£<br><br>Cette action est irréversible !",
	FileExplorer_are_you_sure_copy_paste_fr: "Êtes-vous sûr de vouloir copier/coller £1£ fichier(s) vers £2£ ?",
	FileExplorer_are_you_sure_load_fr: "Êtes-vous sûr de vouloir charger £1£ ?",
	FileExplorer_back_fr: "Retour",
	FileExplorer_cannot_create_unnamed_folder_fr: "Vous ne pouvez pas créer un dossier sans nom.",
	FileExplorer_clear_clipboard_fr: "Vider le presse-papiers",
	FileExplorer_clipboard_fr: "Presse-papiers",
	FileExplorer_clipboard_is_empty_fr: "Le presse-papiers est vide.",
	FileExplorer_create_a_new_file_fr: "Créer un nouveau fichier :",
	FileExplorer_create_new_file_fr: "Créer un nouveau fichier",
	FileExplorer_create_new_folder_fr: "Créer un nouveau dossier",
	FileExplorer_create_a_new_folder_fr: "Créer un nouveau dossier :",
	FileExplorer_created_empty_text_file_fr: "Fichier texte vide créé à : £1£",
	FileExplorer_cut_paste_files_fr: "Couper/Coller £1£ fichiers",
	FileExplorer_confirm_fr: "Confirmer",
	FileExplorer_copied_elements_to_clipboard_fr: "£1£ éléments copiés dans le presse-papiers.",
	FileExplorer_copy_selected_fr: "Copier la sélection",
	FileExplorer_delete_files_fr: "Supprimer £1£ fichiers",
	FileExplorer_do_you_want_to_overwrite_file_fr: "Le fichier existe déjà. Voulez-vous l'écraser ?",
	FileExplorer_elements_selected_fr: "£1£ éléments sélectionnés",
	FileExplorer_error_load_fr: "Erreur lors du chargement du fichier £1£ : £2£",
	FileExplorer_error_load_save_file_fr: "Erreur de chargement de la sauvegarde",
	FileExplorer_load_save_file_fr: "Charger une sauvegarde",
	FileExplorer_loaded_save_file_fr: "Sauvegarde £1£ chargée",
	FileExplorer_move_files_fr: "Déplacer £1£ fichiers",
	FileExplorer_paste_clipboard_fr: "Coller le presse-papiers",
	FileExplorer_paste_files_fr: "Coller £1£ fichiers",
	FileExplorer_rename_fr: "Renommer",
	FileExplorer_save_file_fr: "Enregistrer le fichier",
	FileExplorer_save_file_as_fr: "Enregistrer sous :",
	FileExplorer_select_fr: "Sélectionner",
	FileExplorer_specified_file_path_already_exists_fr: "Le chemin spécifié existe déjà ! Supprimez-le avant de créer un nouveau fichier avec le même nom.",
	FileExplorer_successfully_saved_file_as_fr: "Fichier enregistré avec succès sous : £1£",
	
	//FileExplorer (File Operations)
	FileExplorer_copying_files_to_fr: "Copie de £1£ fichier(s) vers £2£",
	FileExplorer_copying_to_fr: "Copie de £1£ vers £2£",
	FileExplorer_deleting_files_fr: "Suppression de £1£ fichier(s)",
	FileExplorer_deleting_path_fr: "Suppression de £1£",
	FileExplorer_done_fr: "Terminé",
	FileExplorer_error_could_not_be_renamed_fr: "ERREUR : £1£ n'a pas pu être renommé : £2£",
	FileExplorer_eta_remaining_fr: "£1£% - £2£ restants",
	FileExplorer_finished_moving_files_fr: "Déplacement des fichiers terminé",
	FileExplorer_of_progress_fr: "(£1£ sur £2£)",
	FileExplorer_moved_files_fr: "Déplacement de £1£ fichier(s) vers £2£ terminé",
	FileExplorer_rename_file_fr: "Renommer le fichier",
	FileExplorer_rename_file_to_fr: "Renommer le fichier £1£ en :",
	
	//Hierarchy
	Hierarchy_search_for_item_fr: "Rechercher un élément...",
	
	//ScriptManager
	ScriptManager_are_you_sure_clear_console_fr: "Êtes-vous sûr de vouloir effacer la console actuelle ?",
	ScriptManager_clear_blockly_on_error_fr: "Effacer Blockly en cas d'erreur",
	ScriptManager_clear_console_fr: "Effacer la console",
	ScriptManager_codemirror_theme_fr: "Thème Codemirror",
	ScriptManager_console_fr: "Console",
	ScriptManager_could_not_load_settings_fr: "Impossible de charger les paramètres non liés au ScriptManager.",
	ScriptManager_display_load_errors_fr: "Afficher les erreurs de chargement",
	ScriptManager_editor_theme_fr: "Thème de l'éditeur",
	ScriptManager_enter_console_command_fr: "Entrer une commande...",
	ScriptManager_error_compatibility_fr: "Êtes-vous sûr que ce fichier est compatible £1£ ? Blockly a été désactivé et le fichier n'est modifiable que via CodeMirror.",
	ScriptManager_error_loading_settings_fr: "Erreur de chargement des paramètres",
	ScriptManager_error_reading_file_fr: "Erreur de lecture du fichier",
	ScriptManager_help_fr: "Aide",
	ScriptManager_help_menu_fr: "Menu d'aide :",
	ScriptManager_hide_blockly_fr: "Masquer Blockly",
	ScriptManager_hide_show_blockly_fr: "Masquer/Afficher l'espace Blockly en cas d'erreur",
	ScriptManager_load_settings_fr: "Charger les paramètres",
	ScriptManager_none_fr: "Aucun",
	ScriptManager_note_fr: "Note :",
	ScriptManager_keybinds_fr: "Raccourcis clavier",
	ScriptManager_prints_help_information_fr: "Affiche les informations d'aide.",
	ScriptManager_run_fr: "Exécuter",
	ScriptManager_run_current_file_fr: "Exécuter le fichier actuel",
	ScriptManager_run_settings_fr: "Paramètres d'exécution :",
	ScriptManager_save_settings_fr: "Enregistrer les paramètres",
	ScriptManager_saved_settings_fr: "Paramètres enregistrés dans £1£ !",
	ScriptManager_send_fr: "Envoyer",
	ScriptManager_settings_fr: "Paramètres",
	ScriptManager_show_blockly_fr: "Afficher Blockly",
	ScriptManager_stack_trace_fr: "Trace de la pile :",
	ScriptManager_theme_default_fr: "Défaut",
	ScriptManager_theme_light_fr: "Clair",
	ScriptManager_trust_warning_fr: "Assurez-vous de faire confiance au code que vous allez exécuter.",
	ScriptManager_view_fr: "Vue",
	ScriptManager_view_file_explorer_fr: "Voir l'explorateur de fichiers",
	ScriptManager_view_settings_fr: "Paramètres d'affichage",
	
	//SearchSelect
	SearchSelect_no_elements_found_fr: "Aucun élément disponible à rechercher.",
	SearchSelect_search_filter_fr: "Filtre de recherche",
	
	//Button
	Button_confirm_fr: "Confirmer",
	
	//DateLength
	DateLength_days_fr: "Jours",
	DateLength_months_fr: "Mois",
	DateLength_years_fr: "Années",
	
	//File
	File_already_exists_fr: "Le fichier existe déjà. Voulez-vous l'écraser ?",
	File_can_only_select_files_fr: "Vous ne pouvez sélectionner que des fichiers.",
	File_can_only_select_folders_fr: "Vous ne pouvez sélectionner que des dossiers.",
	File_can_only_select_one_file_fr: "Vous ne pouvez sélectionner qu'un seul chemin de fichier/dossier.",
	File_cancel_fr: "Annuler",
	File_confirm_fr: "Confirmer",
	File_error_saving_file_fr: "Erreur d'enregistrement du fichier",
	File_error_saving_file_desc_fr: "Erreur lors de l'enregistrement du fichier : £1£",
	File_must_select_valid_path_fr: "Vous devez sélectionner un chemin de fichier/dossier valide.",
	File_open_file_fr: "Ouvrir un fichier",
	File_open_files_fr: "Ouvrir des fichiers",
	File_open_folder_fr: "Ouvrir un dossier",
	File_open_folders_fr: "Ouvrir des dossiers",
	File_save_file_fr: "Enregistrer le fichier",
	File_save_file_as_fr: "Enregistrer sous...",
	File_select_file_fr: "Sélectionner un fichier",
	File_selected_files_fr: "£1£ fichier(s) sélectionné(s).",
	File_successfully_saved_file_fr: "Fichier enregistré avec succès dans : £1£",
	
	//Interface
	Interface_folder_fr: "Dossier",
	
	//List
	List_delete_item_fr: "Supprimer l'élément",
	List_error_max_items_reached_fr: "La longueur de la liste actuelle ne peut pas dépasser £1£ élément(s).",
	List_error_min_items_reached_fr: "La longueur de la liste actuelle ne peut pas être inférieure à £1£ élément(s).",
	List_info_edit_item_fr: "Modifier l'élément",
	List_insert_item_after_fr: "Insérer après",
	List_insert_item_before_fr: "Insérer avant",
	List_shift_fr: "Décaler",
	List_shift_left_fr: "Décaler à gauche",
	List_shift_right_fr: "Décaler à droite",
	
	//UndoRedo
	UndoRedo_actions_map_fr: "Carte des actions",
	UndoRedo_branch_at_node_fr: "Brancher au nœud",
	UndoRedo_coords_display_fr: "X: £1£, Y: £2£ | Échelle: £3£",
	UndoRedo_initialisation_fr: "S. Init",
	UndoRedo_jump_to_fr: "Aller à",
	UndoRedo_name_fr: "Nom :",
	UndoRedo_split_from_timeline_fr: "Séparer de la timeline",
	UndoRedo_timeline_fr: "Timeline",
	UndoRedo_timeline_view_fr: "Vue chronologique",
	UndoRedo_unlisted_fr: "Non listé",
	
	//Sort filter
	UndoRedo_sorting_filter_fr: "Filtre de tri",
	UndoRedo_sort_timelines_fr: "Trier les timelines :",
	
	//Sort filters
	UndoRedo_alphabetical_ascending_fr: "Alphabétique (A-Z)",
	UndoRedo_alphabetical_descending_fr: "Alphabétique (Z-A)",
	UndoRedo_chronological_ascending_fr: "Chronologique (Croissant)",
	UndoRedo_chronological_descending_fr: "Chronologique (Décroissant)",
	UndoRedo_last_modified_fr: "Dernière modification",
	UndoRedo_least_actions_fr: "Moins d'actions",
	UndoRedo_most_actions_fr: "Plus d'actions",
	
	//WYSIWYG
	WYSIWYG_align_centre_fr: "Centrer",
	WYSIWYG_align_left_fr: "Aligner à gauche",
	WYSIWYG_align_right_fr: "Aligner à droite",
	WYSIWYG_bold_fr: "Gras",
	WYSIWYG_done_fr: "Terminé",
	WYSIWYG_indent_fr: "Indenter",
	WYSIWYG_insert_link_fr: "Insérer un lien",
	WYSIWYG_insert_ordered_list_fr: "Insérer liste ordonnée",
	WYSIWYG_insert_unordered_list_fr: "Insérer liste à puces",
	WYSIWYG_italic_fr: "Italique",
	WYSIWYG_justify_fr: "Justifier",
	WYSIWYG_open_in_new_tab_fr: "Ouvrir dans un nouvel onglet ?",
	WYSIWYG_outdent_fr: "Désindenter",
	WYSIWYG_redo_fr: "Rétablir",
	WYSIWYG_remove_format_fr: "Effacer le formatage",
	WYSIWYG_show_html_code_fr: "Afficher le code HTML",
	WYSIWYG_strikethrough_fr: "Barré",
	WYSIWYG_underline_fr: "Souligné",
	WYSIWYG_undo_fr: "Annuler",
	WYSIWYG_unlink_fr: "Supprimer le lien",
	
	//ve.Feature
	//Confirm
	Confirm_confirm_fr: "Confirmer",
	Confirm_no_fr: "Non",
	Confirm_yes_fr: "Oui",
};